bookmarks/site/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.contrib import admin

from mezzanine.core.views import direct_to_template


admin.autodiscover()

# Add the urlpatterns for any custom Django applications here.
# You can also change the ``home`` view to add your own functionality
# to the project's homepage.

urlpatterns = patterns("",
    ("^admin/", include(admin.site.urls)),

    # We don't want to presume how your homepage works, so here are a
    # few patterns you can use to set it up.

    # HOMEPAGE AS STATIC TEMPLATE
    # ---------------------------
    # This pattern simply loads the index.html template. It isn't
    # commented out like the others, so it's the default. You only need
    # one homepage pattern, so if you use a different one, comment this
    # one out.

    url("^$", direct_to_template, {"template": "index.html"}, name="home"),
    ("^bookmarks/", include("bookmarks.urls")),

    # HOMEPAGE AS AN EDITABLE PAGE IN THE PAGE TREE
    # ---------------------------------------------
    # This pattern gives us a normal ``Page`` object, so that your
    # homepage can be managed via the page tree in the admin. If you
    # use this pattern, you'll need to create a page in the page tree,
    # and specify its URL (in the Meta Data section) as "/", which
    # is the value used below in the ``{"slug": "/"}`` part. Make
    # sure to uncheck "show in navigation" when you create the page,
    # since the link to the homepage is always hard-coded into all the
    # page menus that display navigation on the site. Also note that
    # the normal rule of adding a custom template per page with the
    # template name using the page's slug doesn't apply here, since
    # we can't have a template called "/.html" - so for this case, the
    # template "pages/index.html" can be used.

    # url("^$", "mezzanine.pages.views.page", {"slug": "/"}, name="home"),

    # HOMEPAGE FOR A BLOG-ONLY SITE
    # -----------------------------
    # This pattern points the homepage to the blog post listing page,
    # and is useful for sites that are primarily blogs. If you use this
    # pattern, you'll also need to set BLOG_SLUG = "" in your
    # ``settings.py`` module, and delete the blog page object from the
    # page tree in the admin if it was installed.

    # url("^$", "mezzanine.blog.views.blog_post_list", name="home"),

    # MEZZANINE'S URLS
    # ----------------
    # Note: ADD YOUR OWN URLPATTERNS *ABOVE* THE LINE BELOW.
    # ``mezzanine.urls`` INCLUDES A *CATCH ALL* PATTERN
    # FOR PAGES, SO URLPATTERNS ADDED BELOW ``mezzanine.urls``
    # WILL NEVER BE MATCHED!
    # If you'd like more granular control over the patterns in
    # ``mezzanine.urls``, go right ahead and take the parts you want
    # from it, and use them directly below instead of using
    # ``mezzanine.urls``.
    ("^", include("mezzanine.urls")),

)

# Adds ``STATIC_URL`` to the context of error pages, so that error
# pages can use JS, CSS and images.
handler500 = "mezzanine.core.views.server_error"

bookmarks/urls.py
from django.conf.urls.defaults import url, patterns


urlpatterns = patterns("",
    url(r"^$", "bookmarks.views.bookmarks", name="all_bookmarks"),
    url(r"^(?P<pk>\d+)/$", "bookmarks.views.bookmark", name="bookmark"),
    url(r"^add/$", "bookmarks.views.add", name="add_bookmark"),
    url(r"^extract/$", "bookmarks.views.extract", name="extract_content"),
    url(r"^suggest/$", "bookmarks.views.suggest", name="suggest_content"),
    url(r"^tags/(?P<slug>[-\w]+)/$", "bookmarks.views.bookmarks", name="tagged_bookmarks"),
    url(r"^user/(?P<username>[-\w]+)/$", "bookmarks.views.bookmarks", name="user_bookmarks"),
    url(r"^user/(?P<username>[-\w]+)/tags/(?P<slug>[-\w]+)$", "bookmarks.views.bookmarks", name="user_tagged_bookmarks"),
)

bookmarks/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _

from mezzanine.generic.models import Keyword

from bookmarks.models import Bookmark, Page


class BookmarkForm(forms.ModelForm):
    url = forms.URLField(label="URL", verify_exists=False, widget=forms.TextInput(attrs={"size": 40}))
    title = forms.CharField(max_length=100, widget=forms.TextInput(attrs={"size": 40}))
    keywords = forms.CharField(max_length=100, widget=forms.TextInput(attrs={"size": 40}))
    content = forms.Textarea()
    redirect = forms.BooleanField(label="Redirect", required=False)

    def __init__(self, user=None, *args, **kwargs):
        self.user = user
        super(BookmarkForm, self).__init__(*args, **kwargs)
        # hack to order fields
        self.fields.keyOrder = ["url", "title", "content", "keywords", "redirect"]

    def clean(self):
        if not self.cleaned_data.get("url", None):
            return self.cleaned_data
        if Bookmark.objects.filter(page__url=self.cleaned_data["url"], user=self.user).count() > 0:
            raise forms.ValidationError(_("You have already bookmarked this link."))
        return self.cleaned_data

    def clean_keywords(self):
        """docstring for clean_keywords"""
        ids = []
        for title in self.cleaned_data['keywords'].split(","):
             title = "".join([c for c in title if c.isalnum() or c in "- "])
             title = title.strip().lower()
             if title:
                 keyword, created = Keyword.objects.get_or_create(title=title)
                 id = str(keyword.id)
                 if id not in ids:
                     ids.append(id)
        return ",".join(ids)

    def should_redirect(self):
        if self.cleaned_data["redirect"]:
            return True
        else:
            return False

    def save(self, commit=True):
        try:
            page = Page.objects.get(url=self.cleaned_data['url'])
        except Page.DoesNotExist:
            page = Page.objects.create(url=self.cleaned_data['url'], creator=self.user)

        instance = super(BookmarkForm, self).save(False)
        instance.page = page
        instance.user = self.user

        if commit:
            instance.save()
            self.save_m2m()

        return instance

    class Meta:
        model = Bookmark
        fields = [
            "url",
            "title",
            "content",
            "redirect",
            "keywords",
        ]

bookmarks/templates/bookmarks/add.html
{% extends "base.html" %}

{% load i18n %}

{% block meta_title %}Bookmarks{% endblock %}

{% block title %}
	{% trans "Add Bookmark" %}
{% endblock title %}

{% block main %}
        
    
    <p>You can drag this '<a href="{{ bookmarklet }}">Add to {{ site_name }} Bookmarks</a>' link to your bookmark bar to post the pages you visit!</p>

    <form method="post" action="" id="bookmark_instance_add_form">
    	{% csrf_token %}
        {{ bookmark_form }}
        <p><input type="submit" class="btn btn-primary" value="{% trans 'Submit' %}"> <input id="extract-button" type="button" class="btn btn-primary" value="{% trans 'Extract' %}"> <input id="suggest-button" type="button" class="btn btn-primary" value="{% trans 'Suggest' %}"></p>
    </form>
 <div class="modal hide" id="status">
  <div class="modal-header">
    <h3>Analysing Destination Page</h3>
  </div>
  <div class="modal-body">
    <p id="status_text">Extracting content...</p>
  </div>
</div>
{% endblock %}

{% block extra_js %}
<script type="text/javascript">
$(document).ready(function() {
	function on_tag_clicks(){
		if ($("#id_keywords").val() == "") {
			$("#id_keywords").val($(this).text());
		} else {
			$("#id_keywords").val($("#id_keywords").val() + ", " + $(this).text());
		};
	}

	function extract(){
		$("#status_text").text("Extracting content...");
		$('#status').modal('show');
		$.getJSON('/bookmarks/extract/', {'url':$("#id_url").val()}, function(data){
			$("#id_title").val(data["title"]);
			$("#id_content").val(data["html"]);
			tinyMCE.get('id_content').setContent(data["html"]); 
			$("#id_keywords").after("<div id='tags_extract'></div>");
			$.each(data["tags"], function(index, value){
				$("#tags_extract").append("<span class='label'>"+value+"</span> ");
			})
			$("#tags_extract span").each(function(){
				$(this).click(on_tag_clicks);
			})
			suggest();
		});
	}

	function suggest(){
		$("#status_text").text("Querying suggest tags...");
		$('#status').modal('show');
		$.post('/bookmarks/suggest/', {'content':$("#id_content").val()}, function(data){
			$("#id_keywords").after("<div id='tags_suggest' style='margin-bottom:2px'></div>");
			$.each(data["keywords"], function(index, value){
				$("#tags_suggest").append("<span class='label'>"+value["name"]+"</span> ");
			})
			$("#tags_suggest span").each(function(){
				$(this).click(on_tag_clicks);
			})
			$('#status').modal('hide');
		});
	}


	$("#extract-button").click(extract);
	$("#suggest-button").click(suggest);
	$("#status").modal({keyboard:false, show:false});
	if ($("#id_url").val() != "" && $("#id_content").val() == "") {
		extract();
	};

});
</script>
{% endblock %}

bookmarks/templates/bookmarks/bookmark.html
{% extends "base.html" %}

{% load i18n mezzanine_tags keyword_tags %}

{% block meta_title %}{{ bookmark.title }} | Bookmarks{% endblock %}

{% block content-block %}
<div class="block">
    <div class="block_head">
        <h1>
		    <a href="{{ bookmark.page.url|safe }}"><i class="icon-bookmark"></i> {{ bookmark.title }}</a>
		</h1>
    </div>
    <div class="block_content">
		{% if user.is_authenticated %}
		{{ bookmark.content|safe }}
		{% else %}
		<p>You have to login to see the content of the page.</p>
		{% endif %}
    	<div class="post-meta">
		{% keywords_for bookmark as tags %}
		{% for tag in tags %}
		<i class="icon-tag"></i> <a href="{% url tagged_bookmarks tag.slug %}">{{ tag }}</a>
		{% endfor %}
		</div>
    </div>
</div>

{% endblock %}

bookmarks/templates/bookmarks/bookmarks.html
{% extends "base.html" %}

{% load i18n mezzanine_tags keyword_tags %}

{% block meta_title %}Bookmarks{% endblock %}

{% block content-block %}
{% regroup bookmarks.object_list by publish_date|date:"Y-m-d" as bookmarks_list %}
<div class="block">
    <div class="block_head">
        <h1>
          <i class="icon-bookmark"></i> Bookmarks{% if tag %} tagged with '{{ tag }}'{% endif %}{% if username %} created by '{{ username }}'{% endif %}
		</h1>
    </div>
    <div class="block_content">
    	{% for date_bookmarks in bookmarks_list %}
    		<h2 class="section-title">{{ date_bookmarks.grouper }}</h2>
    		<ul>
    		{% for bookmark in date_bookmarks.list %}
    			<li>
    				<a href="{{ bookmark.page.url }}">{{ bookmark.title }}</a> <a href="{% url bookmark bookmark.pk %}"><i class="icon-caret-right"></i></a><br/>
    				<div class="post-meta">
					{% keywords_for bookmark as tags %}
					{% for tag in tags %}
					<i class="icon-tag"></i> <a href="{% url tagged_bookmarks tag.slug %}">{{ tag }}</a>
					{% endfor %}
    				</div>
    			</li>
    		{% endfor %}
    		</ul>
    	{% endfor %}
    </div>
</div>

{% pagination_for bookmarks %}

{% endblock %}